#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9001/eureka/

# http协议端口 server是https协议端口
server:
  port: 8808

debug: false #开启调试模式与否

spring:
  application:
      name: springTaskService
  main:
    banner-mode: "OFF"
    allow-bean-definition-overriding: true

